### ISSUE TITLE
同步翻译任务认领说明

### ISSUE THREAD

**Issue by elonehoo** [xiaoxunyao/cn.vitest.dev#77]
# 同步翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
> 2. 认领开始前，请务必阅读 [翻译流程说明](https://github.com/vitest-dev/docs-cn/issues/50)
> 3. 如果在翻译的时候发现有任何未同步的地方，及时指出，谢谢！

从 Todo List 中选取未被人领取过的文章：

未被领取过：

-  install

领取过：

-  install ([@elonehoo](https://github.com/elonehoo))

领取过，已完成：

-  install ([@elonehoo](https://github.com/elonehoo)) [docs (cn) : `api/toThrowErrorMatchingSnapshot` translation #49](https://github.com/vitest-dev/docs-cn/pull/49)

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @elonehoo | 2022.05.06 - 2022.05.06
```

示例效果：

| Section | Title   | 译者                                     | 完成时间                |
| ------- | ------- | ---------------------------------------- | ----------------------- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 |

当完成时，请修改自己的认领评论，添加 PR 信息：

| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | install | [@elonehoo](https://github.com/elonehoo) | 2021.05.18 - 2021.05.20 | [#49](https://github.com/vitest-dev/docs-cn/pull/49) |

## 同步翻译的提醒事项

目前的 [main]() 分支是之前的，跟官方文档产生了严重的脱节。

现在的 [dev]() 分支是最新版的，并且后期会每天与官方文档进行同步。

请fork项目之后，将分支调整为 [dev]() 的分支。

```bash
$ git checkout dev
```

将翻译完成的文档 PR 到dev分支。

## 任务认领列表

Todo List:

- [x] guide
  
  - [x] [cli.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/cli.md) ([@watonyweng](https://github.com/watonyweng)) [#2f6c3e4](https://github.com/vitest-dev/docs-cn/commit/2f6c3e4ab71742af30e122acfb6911d2d5194ca0)
  - [x] [comparisons.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/comparisons.md) ([@amadeus711](https://github.com/amadeus711)) - #98
  - [x] [coverage.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/coverage.md) ([@amadeus711](https://github.com/amadeus711)) - #82
  - [x] [debugging.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/debugging.md) ([@amadeus711](https://github.com/amadeus711)) - #85
  - [x] [extending-matchers.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/extending-matchers.md)  ([@justforuse](https://github.com/justforuse)) #81
  - [x] [features.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/features.md) ([@amadeus711](https://github.com/amadeus711)) - #86
  - [x] [filtering.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/filtering.md) ([@amadeus711](https://github.com/amadeus711)) - #90
  - [x] [ide.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/ide.md) ([@watonyweng](https://github.com/watonyweng)) #88
  - [x] [in-source.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/in-source.md) ([@watonyweng](https://github.com/watonyweng)) #92
  - [x] [index.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/index.md) ([@watonyweng](https://github.com/watonyweng)) #84
  - [x] [migration.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/migration.md) ([@watonyweng](https://github.com/watonyweng)) #89
  - [x] [mocking.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/mocking.md) ([@amadeus711](https://github.com/amadeus711)) - #80
  - [x] [snapshot.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/snapshot.md) ([@amadeus711](https://github.com/amadeus711)) - #93
  - [x] [test-context.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/test-context.md) ([@amadeus711](https://github.com/amadeus711)) - #96
  - [x] [ui.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/ui.md) ([@amadeus711](https://github.com/amadeus711)) - #79
  - [x] [using-plugins.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/using-plugins.md) ([@watonyweng](https://github.com/watonyweng)) #95
  - [x] [why.md](https://github.com/vitest-dev/docs-cn/blob/dev/guide/why.md) ([@elonehoo](https://github.com/elonehoo)) #78
- [x] config
  - [x] [index.md](https://github.com/vitest-dev/docs-cn/blob/dev/config/index.md) ([@watonyweng](https://github.com/watonyweng)) #103
- [x] api
  - [x] [index.md](https://github.com/vitest-dev/docs-cn/blob/dev/api/index.md) ([@watonyweng](https://github.com/watonyweng)) #101

**Comment by elonehoo** [comment]
请注意！之前的文档脱节过于严重了，请不要直接复制粘贴，而是与原文进行查看进行翻译。感谢大家

**Comment by elonehoo** [comment]
例如，我产生的问题
![image](https://user-images.githubusercontent.com/43719490/176836198-137eac58-412d-48e4-be9f-52b22096db1c.png)

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | index | [@watonyweng](https://github.com/watonyweng) | 2022.07.01 - 2021.07.05 | #84 |

**Comment by elonehoo** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | why | [@elonehoo](https://github.com/elonehoo) | 2022.07.01 - 2022.07.01 | #78 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | ui | [amadeus711](https://github.com/amadeus711) | 2022.07.01 - 2022.07.01 | #79 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | mocking | [amadeus711](https://github.com/amadeus711) | 2022.07.02 - 2022.07.02 | #80 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | coverage | [amadeus711](https://github.com/amadeus711) | 2022.07.03 - 2022.07.03 | #82 |

**Comment by justforuse** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  extending-matchers | @justforuse | 2022.07.03 | #81

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | Debugging | [amadeus711](https://github.com/amadeus711) | 2022.07.04 - 2022.07.04 | #85 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | ide | [@watonyweng](https://github.com/watonyweng) | 2022.07.05 - 2021.07.06 | #88 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | Features | [amadeus711](https://github.com/amadeus711) | 2022.07.05 - 2022.07.05 | #86  |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | filtering | [amadeus711](https://github.com/amadeus711) | 2022.07.06 - 2022.07.06 | #90 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | migration | [@watonyweng](https://github.com/watonyweng) | 2022.07.06 - 2021.07.07 | #89 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | in-source | [@watonyweng](https://github.com/watonyweng) | 2022.07.07 - 2021.07.08 | #92 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | snapshot | [amadeus711](https://github.com/amadeus711) | 2022.07.07 - 2022.07.08 | #93 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | test-context | [amadeus711](https://github.com/amadeus711) | 2022.07.08 - 2022.07.09 | #96 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | using-plugins | [@watonyweng](https://github.com/watonyweng) | 2022.07.08 - 2021.07.09 | #95 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| api   | index | [@watonyweng](https://github.com/watonyweng) | 2022.07.10 - 2021.07.12 | #101 |

**Comment by XieZongChen** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| guide   | comparisons | [amadeus711](https://github.com/amadeus711) | 2022.07.09 - 2022.07.10 | #98 |

**Comment by watonyweng** [comment]
| Section | Title   | 译者                                     | 完成时间                | PR                                                   |
| ------- | ------- | ---------------------------------------- | ----------------------- | ---------------------------------------------------- |
| config   | index | [@watonyweng](https://github.com/watonyweng) | 2022.07.13 - 2021.07.14 | #103 |
